### ISSUE TITLE
New issue Thomas

### ISSUE THREAD

**Issue by Toxbro** [baelmyhu/chamilo-lms#2]
Comment for the new issue

**Comment by baelmyhu** [comment]
Niquel ! 
![image](https://cloud.githubusercontent.com/assets/4034795/22375773/c1a4c8b2-e4ab-11e6-8114-adc1a22ffc06.png)

**Comment by pielRouge** [comment]
C'est bien!!!

![afaire3](https://cloud.githubusercontent.com/assets/19731545/22375843/fd0d4d52-e4ab-11e6-883c-0ca8fe00a2a1.png)
